### ISSUE TITLE
signal process code part: 404 not found

### ISSUE THREAD

**Issue by yyxr75** [valeoai/RADIal#1]
Hi there,
thanks for your work. this is really a great project for sensor fusion area.
I wonder when can we have the radar signal process code as it shows 404 right now.
Thank you so much.

**Comment by jrebut** [comment]
Hi,

Thank you for your interest.
The signal processing will be released within the next 2 weeks, we are working on the CUDA optimization to run it fast. If it takes too long, we would release the python version

Best
Julien

**Comment by jrebut** [comment]
We released a python version accelerated by CuPy or PyTorch (upon user choice)
