### ISSUE TITLE
Prepared dataset radar doppler clarification

### ISSUE THREAD

**Issue by samberngit** [valeoai/RADIal#11]
Hello,
When looking at the prepared dataset, specifically at the doppler data in radar_PCL, I can not find an explanation on how to interpret this data and can not find an example of usage of this specific data. This is for example not used in the loader/example_dataset.ipynb file.
In the loader/dataset.py file there is a definition of the radar_PCL data as "range,azimuth,elevation,power,doppler,x,y,z,v".
The doppler value is an 8-bit value associated with each datapoint.
How is the doppler value to be interpreted and is there an example which I have missed?

**Comment by jrebut** [comment]
Hi,
The Doppler value is coded on a 8 bits data, from 0 to 255
The zero Doppler is at bin 127.
Positive Doppler, meaning object going away from the sensor, is from 128 to 255
Negative Doppler, meaning object coming toward the sensor, is from 0 to 127
Each Doppler bin as a resolution of 0.1m/s
That is to say the maximum unambiguous velocity is +/- 12.8m/s, roughly speaking +/-50KpH. Everything above will have ambiguity

**Comment by samberngit** [comment]
Thank you for the response!
