### ISSUE TITLE
Placement of label point and heading angle of vehicle

### ISSUE THREAD

**Issue by plpalmer** [valeoai/RADIal#14]
Hello,

Could you eloborate on how exactly the label point is placed? As far as I can see the label is placed mostly in the middle of the back or front of the vehicle, depending on what site is nearest to the ego vehicle, but this doesn’t match for vehicles which are beside the ego vehicle. In these cases the label appears to be placed on the side of the observed vehicle.

As stated in other questions, the bounding box information would also be very helfpful to me. Do you by chance have the heading information of the points on hand to better approximate a bounding box with the provided labels.

Thanks in advance and best regards
Patrick

**Comment by jrebut** [comment]
Hi Patrick,

Your understanding is correct. Labelling was semi-automatic so it might be unperfect especially for vehicle on the side.
We don t have plan now for 3d annotation but it might be something we could consider if there is a large group of person in need of it

Julien
