### ISSUE TITLE
RD_spectrums to RDA tensor

### ISSUE THREAD

**Issue by lightzwc** [valeoai/RADIal#15]
hello , how can I use python to perform 1DFFT on the 2DFFT result of 16 RX in the antenna dimension, and get the range-Doppler-azimuth map. I don't have a good implementation.

**Comment by jrebut** [comment]
Hi,
We do not perform the third FFT to estimate the angle.
Instead, we built a look up table for each azimuth angle and make a cross correlation between the signal and the LUT. An example if provided in the notebook SignalProcessing/radar processing.ipynb
