### ISSUE TITLE
radar parameters

### ISSUE THREAD

**Issue by lightzwc** [valeoai/RADIal#19]
Hello,could you please provide the initial parameters of the radar, such as bandwidth, chirp time, starting frequency, etc., because I want to further process the data, thank you

**Comment by jrebut** [comment]
Hi,
unfortunately, I don t have such information

Julien

**Comment by FrkWang** [comment]
Hello, it is also my interest. Anyone knows the bandwidth, chirp time, frequency, etc. ? Thanks if anyone shares it

**Comment by itberrios** [comment]
You can take a look at the config file: https://drive.google.com/drive/folders/1Zvo2dzRE5hU9VB7S38h_c_ycjusk5eGp?hl=fr
