### ISSUE TITLE
Link to the "ready to use" dataset broken

### ISSUE THREAD

**Issue by WPSanberg** [valeoai/RADIal#2]
Dear authors,

Thanks for creating and sharing this dataset!

Unfortunately, the provided link to the "ready to use" dataset is broken: https://www.dropbox.com/s/bvbndch5rucyp97/RADIal.zip leads to a 'file has been removed' message. Together with the 'page not found error' for the SignalProcessing code (reported in issue #1), this makes it currently difficult to explore the data content fully. 

Can you resolve the broken links or indicate when you expect it to be available?

Thanks in advance!

**Comment by jrebut** [comment]
Hi,

Thank you for your interest.
We are sorry for the broken link, we will investigate the reason why the DopBox link changed. In the meantime, the link has been updated in the ReadMe.
For the SIgnalProcessing, please wait 2 weeks more so that we commit an optimized CUDA version.

Best
Julien
