### ISSUE TITLE
Problem to use the odometry

### ISSUE THREAD

**Issue by chasedreams-jy** [valeoai/RADIal#20]
Hallo,
Thank you for sharing the dataset!
When I used example_sync_reader.ipynb to check the data, I met the following issue. (P.S. I used the same measurement as the original file : RECORD@2020-11-22_12.28.47 )
![image](https://user-images.githubusercontent.com/53898082/167568579-4b7624de-45b2-4bfc-ba2f-10e95f73058c.png)
Any idea how to solve it?

BR
Yi

**Comment by JoeyforJoy** [comment]
您好，您的邮件已经收到，我会尽快给您回复。

**Comment by chasedreams-jy** [comment]
I solve the issue by meself, so I will close it.

**Comment by sri13** [comment]
Can you please share how you resolved the issue?
