### ISSUE TITLE
Complex Valued Neural Networks?

### ISSUE THREAD

**Issue by unfazing** [valeoai/RADIal#22]
Hello, I recently came across complex valued neural networks and would like to inquire if the FFTRadNet model uses complex weights and biases or does it just take in complex data and process the real and imaginary numbers as separately as real inputs?

**Comment by jrebut** [comment]
Hi,

the current implementation does use complex conv, it just stack the real and imag part together.
We did some test initially with complex conv, but we did not noticed better results
