### ISSUE TITLE
Is hard cases trained with the same configuration as the pre-trained model?

### ISSUE THREAD

**Issue by FrkWang** [valeoai/RADIal#23]
The pre-trained model that you provide in the link is for easy cases, right? Did you train the hard cases with the same configuration as the pre-trained model, only thing to adjust is setting the dataset loading 'difficult=True'?

**Comment by jrebut** [comment]
Hi,

the pretrained model is trained with the full dataset (both easy and hard case).
In the training script, difficult is set to True, that is to say the leader uses both hard and easy case.
We have used the flag difficult to False only for the evaluation

**Comment by FrkWang** [comment]
Thank you for the answer
