### ISSUE TITLE
Raw Data Preprocessing

### ISSUE THREAD

**Issue by illaMcbender** [valeoai/RADIal#25]
Hi, thank you for sharing the code!  It is a really great job!
I've been following your work recently and found that you've provided raw dataset and some preprocessing code in SignalProcessing folder.  But I failed to preprocess the raw data into the "ready to use" format that you provided in https://drive.google.com/file/d/1PpAcL5r2PRYMxDb46ASps9YqToL7uJcE/view 
I' m wondering if you can provide the complete code about how to process the raw data into the "ready to use" dataset ?
Thanks a lot!

**Comment by jrebut** [comment]
Hi,

Please, find [here](https://drive.google.com/drive/folders/1WRMAD2R_ZLyVZzA7h3RkpDEWIDQqez-9?usp=sharing) the script to generate the dataset from the raw data.
The script was design at the beginning of the project and the code has been clean-up to be shared. SO, I m not sure it is still compatible with the current signal processing library. ANyway, this is pretty simple, it just saves images, laser data and radar per frame basis 
Please, have a look and let me know if you need further assistance

Julien

**Comment by illaMcbender** [comment]
Thank you so much for your assistance! I will have a try!

**Comment by JeroenBax** [comment]
Hi,
Thanks for the helpfull script, I was wondering which radar processing library you used in this script and if this is still downloadable.

**Comment by sohrab-m** [comment]
Hi, links in the previous comments do not seem to work anymore. I am wondering if you could provided an updated link?
