### ISSUE TITLE
Project Radar to Image space

### ISSUE THREAD

**Issue by Harry-Zhi** [valeoai/RADIal#27]
Hi,

Thanks for the nice work and valuable dataset.

Could you please let me know how to project the received radar data to the image space like Fig1 of your paper?

I would appreciate it if you clould tell me the pipeline or point me to someplace which you recommand?

Thanks!

**Comment by jrebut** [comment]
Hi, 

please, use this code to project 3d point into image space (https://github.com/valeoai/RADIal/blob/main/DBReader/examples/example_laser_projection.ipynb)
Laser and Radar were at the same position, so the code should work fine

Julien

**Comment by Egozjuer** [comment]
@jrebut ,Hello,in the example_laser_projection.ipynb, I only found the rotation_vector and translation_vector from laser lidar to camera coordiante,but how to get the relationship from radar coordinate to camera camera?

**Comment by Egozjuer** [comment]
@jrebut ,Hello,in the example_laser_projection.ipynb, I only found the rotation_vector and translation_vector from laser lidar to camera coordiante,but how to get the relationship from radar coordinate to camera coordinate?

**Comment by goukunpeng** [comment]
@Egozjuer Have you found a solution?

**Comment by goukunpeng** [comment]
@Harry-Zhi Have you found a solution? Do you know how to project the received radar data to the image space?
