### ISSUE TITLE
ID information for tracking

### ISSUE THREAD

**Issue by BaiLiping** [valeoai/RADIal#3]
Hi, can this dataset be used for Multi-object tracking? would it be possible to provide additional ID information on the training set? Thanks

**Comment by jrebut** [comment]
Hi, thank you for your message.
The raw dataset is recorded as sequence so it s possible to track multi objects. However, the annotation we provide is somehow partial, that is to say all the frame are not labelled and there is not a consisten object ID in between frames

Julien
