### ISSUE TITLE
Question about Find Tx0 part in rsp

### ISSUE THREAD

**Issue by shawrby** [valeoai/RADIal#31]
Thanks for the great paper!

What does the code below mean in Find Tx0 part in rpl.py?

![image](https://user-images.githubusercontent.com/54407464/188314443-b4eebd86-09f9-4f12-8be6-1022f16cc4b9.png)

Thank you in advance

**Comment by jrebut** [comment]
Actually, for one object at position [Range,Doppler], the power spectrum contains 12 spots, one for each Tx. In line 175, find_TX0_position aims to identify among the 12 spots, which one is the Tx0.
Then, knowing the doppler position of Tx0, line from 179 to 181 aim to extract all the other Tx position.
That is to say Tx positions will be something like this ([Tx0 Tx0+64*1 Tx0+64*2...]) % 256
