### ISSUE TITLE
RawData_downloadError

### ISSUE THREAD

**Issue by JeroenBax** [valeoai/RADIal#32]
Hi, 

Thanks for the amazing paper.
Unfortunately I can not download the ready-to-use dataset since it crashes after downloading ~65GB out ot 122GB.
Does anyone encounter the same problem?

Thanks in advance!

**Comment by jrebut** [comment]
Hi, I m splitting the archive into several parts to ease the download process.
It should be uploaded tonight to the google drive
Please, check back the github by end of the week

Julien
