### ISSUE TITLE
problem of downing dataset

### ISSUE THREAD

**Issue by sutiankang** [valeoai/RADIal#34]
Thanks for your great work!

Can you provide RADIal part dataset in the form of BaiduPan, because the files always are interrupted after one hour.

Thanks!

**Comment by liululu1** [comment]
> Thanks for your great work!
> 
> Can you provide RADIal part dataset in the form of BaiduPan, because the files always are interrupted after one hour.
> 
> Thanks!

Hi, I use this method to ensure that the download of large files is successful. Download large files from Google Drive App.
[https://blog.csdn.net/qq_36627158/article/details/120587217](url)

**Comment by sutiankang** [comment]
> 

Thanks!

**Comment by sutiankang** [comment]
> > Thanks for your great work!
> > Can you provide RADIal part dataset in the form of BaiduPan, because the files always are interrupted after one hour.
> > Thanks!
> 
> Hi, I use this method to ensure that the download of large files is successful. Download large files from Google Drive App. [https://blog.csdn.net/qq_36627158/article/details/120587217](url)

Thanks!

**Comment by ArthurOuaknine** [comment]
Hi.
Sorry but we don't have any other file storage. Please consider using a more stable internet connection from your side.
