### ISSUE TITLE
Raw-data extraction

### ISSUE THREAD

**Issue by JeroenBax** [valeoai/RADIal#35]
Hi,

I'm trying to recreate the ready to use data set from raw data. In the script that is shared in an earlier issue, a so called label_candidates_0deg.npy is loaded.

What is the function of this file and what does this look like. Or can someone explain te me how I can recreate the data using the signalProcessing library in this project?

Thanks in advance!

**Comment by coding-and-coding** [comment]
> Hi,
> 
> I'm trying to recreate the ready to use data set from raw data. In the script that is shared in an earlier issue, a so called label_candidates_0deg.npy is loaded.
> 
> What is the function of this file and what does this look like. Or can someone explain te me how I can recreate the data using the signalProcessing library in this project?
> 
> Thanks in advance!

hi, the raw data is not available in google drive now, can you share it with me via some ways? thanks!

**Comment by ArthurOuaknine** [comment]
Hello.
We are sorry about the late reply, but also happy to announce that the dataset is back online!
You can access it at this url: https://l.linklyhq.com/l/205Ok
The link is also available in the README of the repository.
Sorry again for the inconvenience.
