### ISSUE TITLE
Unexpected keyword argument 'offset_radar' of DBReader

### ISSUE THREAD

**Issue by zhai-EE** [valeoai/RADIal#37]
Hello,
  When runing signalprocessing/radar_processing, I encountered the following error
  
![image](https://user-images.githubusercontent.com/41221813/192243758-59a33a53-2b3b-4227-904d-c52b4cd6cd59.png)
   Could you please explain the meaning of "offset_radar" and "offset_scala" ?

**Comment by jrebut** [comment]
HI, in the latest DBReader version, these parameters were hardcoded to avoid to play with it. It is basically the time offset in micro second between sensor to be full synchronized.
Please, discard these parameters and keep the tolerance to 40000 (40ms)

Julien

**Comment by zhai-EE** [comment]
Thank you！
