### ISSUE TITLE
Downloading Error Issue

### ISSUE THREAD

**Issue by ChidanandKumarKS** [valeoai/RADIal#39]
I have downloaded RADIal.zip from location "https://drive.google.com/drive/folders/1RFRoJJd9ghfjRHjA8t_POwGzYdoUA1IY".

Even after getting completly downloaded, the extraction error thrown in the above snapshot. Kindly look into the above issue.
![Valeo_DownloadError](https://user-images.githubusercontent.com/25030434/193219170-a7d517dc-4e5f-4de6-87ad-b95f48b42bec.png)

**Comment by ArthurOuaknine** [comment]
Hi.
First verify if the data have been correctly downloaded, i.e. no early break, break during the download and so on.
If it is ok, try to extract the data manually using unzip. You have to use a specific command to extract .z0X files. Note that all the .z0X files are required to extract the entire dataset.
Please have a look to this issue: https://askubuntu.com/questions/31298/how-to-extract-and-join-files-xxx-zip-xxx-z01-and-xxx-z02
