### ISSUE TITLE
Labels for raw data

### ISSUE THREAD

**Issue by Kshitizbansal** [valeoai/RADIal#4]
Hi,

Thank you for the release of this data. The released raw data does not seem to have the accompanying label files. I understand that only ~8000 frames have been labeled which are present as CSV in the given processed data, but is there a way to find out which frames from the raw data have been labeled?

Also, the frame numbers are not continuous in the processed sample data, is it correct to assume that the labeled data is not continuous?  Please let me know
![image](https://user-images.githubusercontent.com/17097706/149015514-6b9582ca-f211-4e6e-bed7-83b1e8967f9f.png)

Thanks

**Comment by jrebut** [comment]
Hi,
the CSV file contains a column named **dataset** which is the name of sequence used and another column **Index** which is the index of the frame within the sequence.
As an example, the num sample 18 has 4 labels, from the sequence RECORD@2020-11-21_13.44.44 at the frame index 26.
To read its corresponding data, you should use the following syntax:
`from DBReader.DBReader import SyncReader
db = SyncReader(folder="RECORD@2020-11-21_13.44.44",tolerance=40000,offset_radar = -180000,offset_scala = -40000)
sample = db.GetSensorData(26)`

Finally, you are right, the labelled frame are not continuous

Julien
