### ISSUE TITLE
Are you using a 4D millimeter wave radar?

### ISSUE THREAD

**Issue by chenhengwei1999** [valeoai/RADIal#40]
I can see in Figure 1 (a) of your published paper that the RADAR point cloud projected into the image has height information, but most of the existing vehicle borne 3D millimeter wave radars do not have height measurement capability, so I want to ask if you use 4D millimeter wave radar?

![1664602608077](https://user-images.githubusercontent.com/63592913/193394382-618836f8-b2bd-47c4-8e4d-697046a6e5a2.png)

**Comment by waqasmalik85** [comment]
Yes, it is a 4D imaging radar with 192 virtual channels

**Comment by Nick-Sun1018** [comment]
Does it the AWR2243 from TI?
