### ISSUE TITLE
Download Dataset

### ISSUE THREAD

**Issue by JobNam** [valeoai/RADIal#62]
Hello.
I am a graduate student with a research focus on millimeter-wave radar. I would like to request access to the RADIaI dataset you have provided for learning purposes. However, I encountered access issues when attempting to download it. I would like to inquire if it would be possible to obtain your permission to access and download this dataset. 
Sincerely, thank you!
![image](https://github.com/valeoai/RADIal/assets/102002155/649034cb-ac77-4aed-b0aa-c540e32ce4e2)

**Comment by bao-decheng** [comment]
Hello, I also encountered the same problem. Have you solved your problem?

**Comment by ArthurOuaknine** [comment]
Hi, thanks for your interest in our work.
Due to the some issues we encounter with the storage, the data is temporarily unavailable. We are currently working on a new solution to make the dataset available again as soon as possible. Thank you for your patience and understanding. We apologize for the inconvenience.

**Comment by vbhvdnsh** [comment]
I could access the "ready to use" data from Google Drive but it still seems to be missing the "labels.csv" file. I think the same is critical to use the data (numpy array files) downloaded and for network evaluation/test run. Could you please provide access to the same?

**Comment by ArthurOuaknine** [comment]
Hello.
We are sorry about the late reply, but also happy to announce that the dataset is back online!
You can access it at this url: https://l.linklyhq.com/l/205Ok
The link is also available in the README of the repository.
Sorry again for the inconvenience.
