### ISSUE TITLE
Downloading unavailable

### ISSUE THREAD

**Issue by Toytiny** [valeoai/RADIal#68]
Hi,

Great work and high-quality data! May I ask when the data storage can be recovered for downloading?

**Comment by coding-and-coding** [comment]
i want to know when can the "ready to use" be downloaded too!

**Comment by ArthurOuaknine** [comment]
Hi.
As mentioned in the README, we have storage issues for the dataset.
A new storage has been found but accessibility issues remain, the person in charge is working on it.
We will let you know as soon as possible, we are really sorry about the inconvenience.

**Comment by ArthurOuaknine** [comment]
Hello.
We are sorry about the late reply, but also happy to announce that the dataset is back online!
You can access it at this url: https://l.linklyhq.com/l/205Ok
The link is also available in the README of the repository.
Sorry again for the inconvenience.
