### ISSUE TITLE
The raw data is not available in google drive now, can you share it with me via some ways? thanks!

### ISSUE THREAD

**Issue by coding-and-coding** [valeoai/RADIal#69]
@ArthurOuaknine @jrebut @julienRebut @abursuc @ptrckprz 
**hi, the raw data is not available in google drive now, can you share it with me via some ways? thanks!**

**Comment by ezhovv** [comment]
@coding-and-coding, please let me know if you were able to access the dataset. I'm stuck in a similar situation.

**Comment by coding-and-coding** [comment]
> @coding-and-coding, please let me know if you were able to access the dataset. I'm stuck in a similar situation.

the link https://drive.google.com/drive/folders/1JHPLQsjwtO0SOgAgkq8KOqXndKaOGwFM?usp=sharing_eip_m&ts=65c190d1, which is from the author

**Comment by ArthurOuaknine** [comment]
Hi.
As mentioned in the README, we have storage issues for the dataset.
A new storage has been found but accessibility issues remain, @F-Barto is working on it. 
We will let you know as soon as possible, we are really sorry about the inconvenience.

**Comment by coding-and-coding** [comment]
> Hi. As mentioned in the README, we have storage issues for the dataset. A new storage has been found but accessibility issues remain, @F-Barto is working on it. We will let you know as soon as possible, we are really sorry about the inconvenience.

thanks for your replay!

**Comment by coding-and-coding** [comment]
> Hello. We are sorry about the late reply, but also happy to announce that the dataset is back online! You can access it at this url: https://l.linklyhq.com/l/205Ok The link is also available in the README of the repository. Sorry again for the inconvenience.

thanks a lot!
