### ISSUE TITLE
Any idea when this dataset will become available again?

### ISSUE THREAD

**Issue by rastna12** [valeoai/RADIal#70]
It seems to be well received by the community and I would like to use it for my work.

**Comment by ArthurOuaknine** [comment]
Hello.
Unfortunately, we haven't heard from the company storing the data for several months.
We hope to have more information soon and we will let you know accordingly.
Maybe @F-Barto could provide more info?

**Comment by Nachtraven** [comment]
Would also be interested in the link or hosting information!

**Comment by ArthurOuaknine** [comment]
FYI, a new storage has been found but accessibility issues remain, the person in charge is working on it. 
We will let you know as soon as possible, we are really sorry about the inconvenience.

**Comment by ZuoTisheng201** [comment]
> FYI, a new storage has been found but accessibility issues remain, the person in charge is working on it. We will let you know as soon as possible, we are really sorry about the inconvenience.

Hi, did you guys succeed? Is the dataset ready for download?

**Comment by ffent** [comment]
@ArthurOuaknine is there any update on this?

**Comment by ArthurOuaknine** [comment]
Hi, things are moving forward, the team in charge is waiting for a final security validation to be able to start the upload of the dataset.
It's difficult for me to evaluate how much time it will take, hopefully less than a month.
I will let you know asap when the dataset is available.
Sorry again for the inconvenience.

**Comment by StZhang-B** [comment]
@ArthurOuaknine how long will it take for the RADIAL dataset to be released again?

**Comment by ArthurOuaknine** [comment]
Hello, I've had recent news from last week. The (long) process is still ongoing but the dataset reached the last step before being released again.
The team in charge is waiting for a last green flag before pushing the link to the dataset here, hopefully in a few weeks.
@F-Barto please let us know when it's available.
Sorry again for the inconvenience.

**Comment by ArthurOuaknine** [comment]
Hello.
We are sorry about the late reply, but also happy to announce that the dataset is back online!
You can access it at this url: https://l.linklyhq.com/l/205Ok
The link is also available in the README of the repository.
Sorry again for the inconvenience.
