### ISSUE TITLE
Test dataset

### ISSUE THREAD

**Issue by svaziri1986** [valeoai/RADIal#72]
Hey, I need at least the test or evaluation dataset to reproduce the result. Is it possible to provide it at your earliest convenience?

**Comment by ArthurOuaknine** [comment]
Hello.
We are sorry about the late reply, but also happy to announce that the dataset is back online!
You can access it at this url: https://l.linklyhq.com/l/205Ok
The link is also available in the README of the repository.
Sorry again for the inconvenience.
