### ISSUE TITLE
Can I upload the dataset to a network disk in mainland China and share it?

### ISSUE THREAD

**Issue by Cao-Zonghan** [valeoai/RADIal#73]
Because it is difficult to use Google Cloud Drive in mainland China, can I upload the data set to Google Cloud Drive in mainland China and share it? I will indicate the source and corresponding link in the uploaded file.Or I will give you the shared URL directly, and you can write it directly into the readme.

**Comment by ArthurOuaknine** [comment]
Hello.
To the best of my knowledge, we have not set any restrictions on which countries can use the dataset. 
Please feel free to share it in China by referring to our publication and repository. 
CC @waqasmalik85, let us know if there is anything that could go against this usage.

**Comment by waqasmalik85** [comment]
Hello, there are no restrictions to download from anywhere around the world. Mainland China IP addresses have already downloaded multiple times.

**Comment by waqasmalik85** [comment]
Can you share tge screenshot of the error you see? Just to make sure that you have access to the data.

**Comment by Cao-Zonghan** [comment]
> Can you share tge screenshot of the error you see? Just to make sure that you have access to the data.

Hello, I personally can download data from Google Cloud Drive. However, it is usually difficult for most people from mainland China to log in to Google Cloud Drive and obtain corresponding services. Generally, we will use a VPN to solve this problem. But VPNs often limit download speeds, sometimes to just a few hundred KB per second. It took me three days to download all the data you provided.

**Comment by waqasmalik85** [comment]
Now I understand the problem. Which platform would you use for the data upload? Baidu etc? feel free to write me an e mail at waqas.malik@valeo.com and we can find a right solution to this problem.

**Comment by prograguo** [comment]
> > Can you share tge screenshot of the error you see? Just to make sure that you have access to the data.
> 
> Hello, I personally can download data from Google Cloud Drive. However, it is usually difficult for most people from mainland China to log in to Google Cloud Drive and obtain corresponding services. Generally, we will use a VPN to solve this problem. But VPNs often limit download speeds, sometimes to just a few hundred KB per second. It took me three days to download all the data you provided.

Excuse me, have you uploaded Baidu Cloud，Can you share it？

**Comment by Cao-Zonghan** [comment]
Sorry, I just saw the email today. I will give you the corresponding Baidu Cloud link.
RADIal
Link: https://pan.baidu.com/s/12peKa1nU9Mx-8a-XOgtT_g?pwd=79ee
Password: 79ee
--

在2025-04-02 ***@***.***写道：

Can you share tge screenshot of the error you see? Just to make sure that you have access to the data.

Hello, I personally can download data from Google Cloud Drive. However, it is usually difficult for most people from mainland China to log in to Google Cloud Drive and obtain corresponding services. Generally, we will use a VPN to solve this problem. But VPNs often limit download speeds, sometimes to just a few hundred KB per second. It took me three days to download all the data you provided.

Excuse me, have you uploaded Baidu Cloud，Can you share it？

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

prograguo left a comment (valeoai/RADIal#73)

Can you share tge screenshot of the error you see? Just to make sure that you have access to the data.

Hello, I personally can download data from Google Cloud Drive. However, it is usually difficult for most people from mainland China to log in to Google Cloud Drive and obtain corresponding services. Generally, we will use a VPN to solve this problem. But VPNs often limit download speeds, sometimes to just a few hundred KB per second. It took me three days to download all the data you provided.

Excuse me, have you uploaded Baidu Cloud，Can you share it？
