### ISSUE TITLE
Release of Full resolution data

### ISSUE THREAD

**Issue by Harry-Zhi** [valeoai/RADIal#9]
Hi.

Just want to ask when the full resolution data are planned to released?
Quite look forward to that.

**Comment by JoeyforJoy** [comment]
您好，您的邮件已经收到，我会尽快给您回复。

**Comment by jrebut** [comment]
Hi, we are currently working on the anonimization. License plates were done yesterday and faces should be done by end of the week. I believe the dataset should be uploaded over the week end on Google server.

Stay tuned!
Julien
